"""Write the JSON Schemas and golden fixtures to `contracts/`.

Run `python -m trustrail.contracts.export` after changing a model. The output is
deterministic — fixed keys, a fixed instant — so a clean `git diff` means the
wire contract did not move, and a dirty one is the signal to tell the other
workstreams.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

from pydantic import BaseModel

from trustrail.contracts.scenarios import Scenario, build_scenarios, demo_config
from trustrail.models.audit import AuditEntry
from trustrail.models.charge import Charge
from trustrail.models.evaluation import EvaluatorOutput, SignedEvaluatorOutput
from trustrail.models.mandate import Mandate, MandateBinding, SignedMandate
from trustrail.models.registry import AgentRecord, MerchantRecord
from trustrail.models.verdict import Verdict
from trustrail.models.verification import VerificationRequest
from trustrail.verifier.service import VerifierService

#: The models other workstreams build against. Anything not on this list is an
#: internal detail they should not be coding to.
PUBLISHED_MODELS: tuple[type[BaseModel], ...] = (
    Mandate,
    SignedMandate,
    MandateBinding,
    Charge,
    EvaluatorOutput,
    SignedEvaluatorOutput,
    MerchantRecord,
    AgentRecord,
    VerificationRequest,
    Verdict,
    AuditEntry,
)


def export(root: Path) -> None:
    """Regenerate `contracts/` in place."""
    scenarios = build_scenarios()
    _write_schemas(root / "schemas")
    _write_fixtures(root / "fixtures", scenarios)
    _write_index(root / "FIXTURES.md", scenarios)


def _write_schemas(directory: Path) -> None:
    """Write each published model's *serialisation* schema.

    Serialisation rather than the default, because these files answer "what will
    I receive", and computed fields exist only in that mode. Under the default,
    `Verdict.failed_deterministically` was missing from the published schema
    entirely -- the one field the approval UI must obey to avoid offering a
    button that clicks past a bad signature.

    Only `Verdict` and `AuditEntry` (which embeds one) differ between the two
    modes; every other published model is byte-identical either way, because a
    model with no computed fields serialises exactly as it validates.
    """
    directory.mkdir(parents=True, exist_ok=True)
    for model in PUBLISHED_MODELS:
        _write_json(
            directory / f"{model.__name__}.json",
            model.model_json_schema(mode="serialization"),
        )


def _write_fixtures(directory: Path, scenarios: list[Scenario]) -> None:
    directory.mkdir(parents=True, exist_ok=True)
    for scenario in scenarios:
        _write_json(
            directory / f"{scenario.name}.json",
            {
                "name": scenario.name,
                "description": scenario.description,
                "expected": {
                    "decision": scenario.expected_decision.value,
                    "reason_codes": [r.value for r in scenario.expected_reasons],
                },
                "request": scenario.request.model_dump(mode="json"),
            },
        )


def _write_index(path: Path, scenarios: list[Scenario]) -> None:
    """A table of what each fixture proves, generated so it cannot go stale."""
    verifier = VerifierService(demo_config())
    rows = [
        "| Fixture | Decision | Reason codes | What it proves |",
        "| --- | --- | --- | --- |",
    ]
    for scenario in scenarios:
        verdict = verifier.verify(scenario.request)
        codes = ", ".join(f"`{code}`" for code in verdict.reason_codes) or "—"
        rows.append(
            f"| `{scenario.name}` | **{verdict.decision}** | {codes} | "
            f"{scenario.description} |"
        )
    header = (
        "# Fixtures\n\n"
        "Generated by `python -m trustrail.contracts.export`. Each fixture is a "
        "complete `VerificationRequest` and the verdict the Verifier must return "
        "for it. The table below is produced by running the Verifier over them, "
        "so it cannot drift from actual behaviour.\n\n"
    )
    _write_text(path, header + "\n".join(rows) + "\n")


def _write_json(path: Path, payload: object) -> None:
    _write_text(path, json.dumps(payload, indent=2, ensure_ascii=False) + "\n")


def _write_text(path: Path, content: str) -> None:
    """Write generated output identically on every platform.

    Both arguments are load-bearing, and the default for each is wrong here:

    - ``encoding`` because the output is deliberately non-ASCII (``ensure_ascii=False``, plus
      em-dashes in the prose). Without it Python uses the platform default, which is cp1252 on
      Windows, and every dash becomes a replacement character.
    - ``newline`` because text mode otherwise translates ``\\n`` to ``os.linesep``, giving CRLF
      on Windows and LF everywhere else. That would leave the bytes on disk depending on who
      ran the export, and whether the diff looked clean depending on their ``core.autocrlf``.

    The promise this file makes is that a clean ``git diff`` means the wire contract did not
    move. That promise has to hold for a reviewer on macOS reading a commit made on Windows.
    """
    path.write_text(content, encoding="utf-8", newline="\n")


def _default_root() -> Path:
    # src/trustrail/contracts/export.py -> repository root
    return Path(__file__).resolve().parents[3] / "contracts"


if __name__ == "__main__":
    destination = Path(sys.argv[1]) if len(sys.argv) > 1 else _default_root()
    export(destination)
    print(f"wrote schemas and fixtures to {destination}")
