"""The whole rail in one process: the demo composition root.

Everything else is deliberately partial. `trustrail.app.create_demo_app` runs
the Mandate Service and Verifier with no agents; `app.main.create_app` runs the
stub marketplace with no rail. This is the only module that imports both, which
is why the wiring nobody else can do — registering merchants and agents,
pointing the Browser Agent at a marketplace, handing the Evaluator its key —
happens here.

In deployment these are separate services and this file is replaced by
configuration. What it encodes that configuration must also encode:

- The Verifier trusts the *address* of whatever key the Mandate Service signs
  with. Wire one and forget the other and every mandate fails its signature.
- The Merchant Registry's payout address is agreed with the platform. The
  marketplace also publishes an address in its listings, and the two being
  equal is what the Verifier checks. Deriving one from the other here would
  make the check vacuous, so both are stated.
- Both of the Evaluator's ids are registered. It reports `evaluator-rules-v1`
  when its model is unreachable and `evaluator-hybrid-nova-v1` when it is not,
  and an unregistered id is a deterministic FAIL.
"""

from __future__ import annotations

from dataclasses import dataclass
from decimal import Decimal

from fastapi import FastAPI
from trustrail.app import create_app
from trustrail.clock import SystemClock
from trustrail.mandate.service import MandateService
from trustrail.models.money import Money
from trustrail.models.registry import AgentRole
from trustrail.orchestrator.onboarding import OnboardingOrchestrator
from trustrail.orchestrator.purchase import PurchaseOrchestrator
from trustrail.settlement.models import SettlementReceipt
from trustrail.settlement.queue.memory import InMemorySettlementQueue
from trustrail.settlement.rails.base import SettlementRail
from trustrail.settlement.wiring import ChainWiring
from trustrail.settlement.worker import SettlementWorker
from trustrail.signing.eip712 import Eip712Domain
from trustrail.signing.local import LocalSigner
from trustrail.stores.memory import (
    InMemoryAgentDirectory,
    InMemoryAuditLog,
    InMemoryKillSwitchStore,
    InMemoryMandateStore,
    InMemoryMerchantDirectory,
    InMemoryReviewHoldStore,
)
from trustrail.verifier.config import VerifierConfig
from trustrail.verifier.service import VerifierService

from app.agents.browser import BrowserAgent, ListingsClient
from app.agents.evaluator import EvaluatorAgent
from app.agents.rail_adapter import BrowserAndEvaluator
from app.contracts import ListingsResponse
from app.main import build_marketplace_service
from app.marketplace.routes import create_marketplace_router
from app.marketplace.service import MERCHANT, MarketplaceService, SettlementProfile

BROWSER_AGENT_ID = "browser-agent-1"


class DirectListingsClient:
    """A `ListingsClient` that calls the marketplace in this same process.

    The demo runs the stub marketplace and the rail together, so an HTTP client
    would have to reach a server that is not listening yet. Going straight at
    the service keeps the parts that matter real — quote ids, expiry, and the
    basket hash are all generated by the marketplace exactly as they would be
    over the wire — while skipping only the transport.

    Point `HttpListingsClient` at a URL instead and nothing above this changes.
    """

    def __init__(self, marketplace: MarketplaceService) -> None:
        self._marketplace = marketplace

    async def fetch_listings(
        self, *, q: str, max_price: Money, currency: str = "XSGD"
    ) -> ListingsResponse:
        return self._marketplace.list_items(
            q=q, max_price=Decimal(max_price.amount), currency=currency
        )


@dataclass
class Rail:
    """Every part of the assembled rail, kept reachable for tests and the demo."""

    app: FastAPI
    mandates: MandateService
    verifier: VerifierService
    orchestrator: PurchaseOrchestrator
    onboarding: OnboardingOrchestrator
    marketplace: MarketplaceService
    merchants: InMemoryMerchantDirectory
    queue: InMemorySettlementQueue
    audit: InMemoryAuditLog
    evaluator_signer: LocalSigner
    worker: SettlementWorker | None = None
    chain: ChainWiring | None = None

    def settle_pending(self, limit: int = 10) -> list[SettlementReceipt]:
        """Drain the settlement queue now, synchronously.

        In deployment the worker is its own process polling SQS. Here it is a
        method, because a demo and a test both want to say "and then it
        settled" at a specific point rather than racing a background thread.
        Returns a receipt per message: SETTLED, REFUSED or ERROR.
        """
        if self.worker is None:
            return []
        return self.worker.process_once(limit=limit)


def build_rail(
    *,
    listings_client: ListingsClient | None = None,
    preferred_sku: str | None = None,
    domain: Eip712Domain | None = None,
    evaluator_model: object | None = None,
    chain: ChainWiring | None = None,
    issuer: LocalSigner | None = None,
    settlement_rail: SettlementRail | None = None,
) -> Rail:
    """Assemble the whole rail, with the stub marketplace in the same process.

    `listings_client` defaults to calling that marketplace directly. Pass an
    `HttpListingsClient` instead to shop a merchant that is genuinely remote —
    which is the configuration a real deployment has, and the reason the
    Browser Agent takes a client at all.

    `chain` turns this from a simulation into something that moves money.
    Supply it and mandates are registered onchain at mint, and a PASS settles
    by calling `MandateRegistry.spend`. Leave it out and nothing touches a
    network: mandates are signed and stored, verdicts are reached, and the
    settlement queue fills up with charges nobody executes.

    `issuer` must be the key holding REGISTRAR_ROLE when `chain` is supplied —
    the Mandate Service is what registers, so its signer is the registrar. A
    generated key would sign valid mandates that the contract refuses to record.
    """
    # When there is a chain, the marketplace quotes against what was actually
    # deployed. Otherwise its 402s would advertise a zero asset address on
    # whichever network the defaults happen to name — a merchant asking to be
    # paid in a token that does not exist.
    marketplace = build_marketplace_service(
        SettlementProfile.from_deployment(chain.deployment) if chain else None
    )
    listings_client = listings_client or DirectListingsClient(marketplace)

    issuer = issuer or LocalSigner.generate()
    evaluator_signer = LocalSigner.generate()

    mandate_store = InMemoryMandateStore()
    audit = InMemoryAuditLog()
    merchants = InMemoryMerchantDirectory()
    agents = InMemoryAgentDirectory()
    holds = InMemoryReviewHoldStore()
    queue = InMemorySettlementQueue()

    mandates = MandateService(
        signer=issuer,
        store=mandate_store,
        kill_switch=InMemoryKillSwitchStore(),
        audit=audit,
        domain=domain,
        registrar=chain.registrar if chain else None,
    )
    # The Verifier is told the issuer's address, never its key. That is the
    # same relationship production has, where the key never leaves KMS.
    config = VerifierConfig(
        issuer_address=issuer.address, domain=domain or Eip712Domain()
    )
    verifier = VerifierService(config)

    onboarding = OnboardingOrchestrator(merchants=merchants, agents=agents)
    _seed(onboarding, evaluator_address=evaluator_signer.address)

    evaluator = EvaluatorAgent(model=evaluator_model)
    shopper = BrowserAndEvaluator(
        browser=BrowserAgent([listings_client]),
        evaluator=evaluator,
        signer=evaluator_signer,
        preferred_sku=preferred_sku,
    )
    orchestrator = PurchaseOrchestrator(
        mandates=mandates,
        verifier=verifier,
        config=config,
        shopper=shopper,
        merchants=merchants,
        agents=agents,
        holds=holds,
        queue=queue,
    )

    app = create_app(
        mandates=mandates,
        verifier=verifier,
        orchestrator=orchestrator,
        onboarding=onboarding,
        merchants=merchants,
        agents=agents,
    )
    app.include_router(create_marketplace_router(marketplace))

    return Rail(
        app=app,
        mandates=mandates,
        verifier=verifier,
        orchestrator=orchestrator,
        onboarding=onboarding,
        marketplace=marketplace,
        merchants=merchants,
        queue=queue,
        audit=audit,
        evaluator_signer=evaluator_signer,
        worker=_worker(queue, audit, settlement_rail or (chain.rail if chain else None)),
        chain=chain,
    )


def _worker(
    queue: InMemorySettlementQueue,
    audit: InMemoryAuditLog,
    rail: SettlementRail | None,
) -> SettlementWorker | None:
    """A worker, if there is a rail for it to settle on.

    No rail means no worker, and the queue simply fills — which is the honest
    state of an offline run. The alternative, defaulting to the card rail's
    local fake, would have a demo cheerfully report SETTLED for money that
    never moved.
    """
    if rail is None:
        return None
    return SettlementWorker(
        queue=queue,
        rails={rail.name: rail},
        audit=audit,
        clock=SystemClock(),
        rail_name=rail.name,
    )


def demo_app() -> FastAPI:
    """The whole rail as an ASGI app, for `uvicorn --factory app.rail:demo_app`.

    Selection is left free here rather than pinned to a SKU, so the Browser
    Agent picks by price the way it actually would. That means the S$0.50
    listing from the unrated seller wins and the first purchase lands in
    REVIEW — which is the honest default, and the demo beat worth opening on.
    Pin `preferred_sku` through `build_rail` to walk the other scenarios.
    """
    return build_rail().app


def _seed(onboarding: OnboardingOrchestrator, *, evaluator_address: str) -> None:
    """Register the demo counterparties.

    The payout address is written out rather than read from `MERCHANT`, even
    though they are the same value here. The registry's copy is what we agreed
    with the platform; the marketplace's copy is what it publishes. The
    Verifier compares them, and the comparison only means something while the
    two have independent sources.
    """
    onboarding.register_merchant(
        merchant_id=MERCHANT.id,
        name=MERCHANT.name,
        payout_address="0x5DC6eBd1745c4c58f73D846952E5d4a8858763cc",
    )
    # The Browser Agent gets an identity even though it signs nothing yet. That
    # is the honest state of CLAUDE.md's "every agent signs its output": the
    # registry slot is real, the Evaluator uses it, and the Browser Agent's
    # signing is not built. Registering it now means the audit trail already
    # names the agent that shopped, and adding its signature later changes no
    # interface.
    onboarding.register_agent(
        agent_id=BROWSER_AGENT_ID,
        role=AgentRole.BROWSER,
        address=LocalSigner.generate().address,
    )
    onboarding.register_evaluator(
        agent_ids=(
            EvaluatorAgent.rules_evaluator_id,
            EvaluatorAgent.hybrid_evaluator_id,
        ),
        address=evaluator_address,
    )
